### ISSUE TITLE
mysqldump pre-command doesnt work

### ISSUE THREAD

**Issue by swayoleg** [frdmn/tar-multibackup#4]
Config

```
pre_commands=(
    "mysqldump mydbnme -u myusername -pmypassword | bzip2 -c > /var/www/somesite/db_$(date +%Y-%m-%d).sql.bz2"
)

# Commands that are executed after the backup is completed
post_commands=(
    "rm /var/www/somesite/db_$(date +%Y-%m-%d).sql.bz2"
)
```

When I run this commands directly in bash, it works fine.
The script is working also fine, it backups only the folder from config file, so the config file is readeble by the sript.

If I run the script with output it will show my mysqldump full command, but dont even wait for it, and no file is created.

**Comment by frdmn** [comment]
Which OS do you use?

**Comment by swayoleg** [comment]
Ubuntu 14 LTS,
same on ubuntu 16 LTS

* with "no file is created" I mean no mysqldump file is created. Just showing me dump command and dont wait for it. 
+ If I hardcode my mysqldump command directly in the script and it works fine, waiting and dumpiung and only then makes tar.

**Comment by frdmn** [comment]
> If I hardcode my mysqldump command directly in the script

What command (exactly) did you run? Can you paste here?

**Comment by swayoleg** [comment]
I'll try to explain once more.

**The target** - dump database to sql.bz2 to website folder before packing website (to backup database as well), and remove that bz2 after packing is done (to avoid a milliard dumps).

Here is the command I need to run before packing a files
 `mysqldump mydbnme -u myusername -pmypassword | bzip2 -c > /var/www/somesite/db_$(date +%Y-%m-%d).sql.bz2`

Where **mydbnme myusername mypassword** and **somesite** are real values (please believe me, just don't want to share production data of the customer)

If I run this command 
`mysqldump mydbnme -u myusername -pmypassword | bzip2 -c > /var/www/somesite/db_$(date +%Y-%m-%d).sql.bz2`
 at server bash, I get the **db_2017-02-13.sql.bz2** file, which is dumped correctly, I can open it, etc...

When I write this 
 `mysqldump mydbnme -u myusername -pmypassword | bzip2 -c > /var/www/somesite/db_$(date +%Y-%m-%d).sql.bz2`
to your bash script directly at multibackup file (which is not correct way, I know) at line 108 for example, It will dump  me a sql.bz2 file as well. Which will be also correct dump etc...

But I assume it should be run via config updates.

Here is config update:

pre_commands=(
    "mysqldump mydbnme -u myusername -pmypassword | bzip2 -c > /var/www/somesite/db_$(date +%Y-%m-%d).sql.bz2"
)
post_commands=(
    "rm /var/www/somesite/db_$(date +%Y-%m-%d).sql.bz2"
)

When I run bash multibackup with output, I will see that line
` info "Running \"${pre_command}\":"` 
will show me my command (which is directly the same, I type directly in the bash, or hardcode it into your script), **BUT the next second it will show me success message, without any timeout** (it usually takes about 45-50 sec with my database), and at that moment no sql bz file is found and, it starts packing a website folder....

So it seems that it only shows info messages what commands should be run, but don't run commands actually....

Makes sense ?

**Comment by frdmn** [comment]
Okay, the reason I was asking for the complete command, was to rule out that you didn't miss any of the pipes, thus the script waiting for stdout/stdin.

Now, please try to use single quotes instead of double ones (make sure to expand any used variable, since variables won't translated within single quotes):

```
pre_commands=(
    'mysqldump mydbnme -u myusername -pmypassword | bzip2 -c > /var/www/somesite/db_$(date +%Y-%m-%d).sql.bz2'
)
```

If that still doesn't change anything, revert the quote changes and run the script like this for debug output:

```
DEBUG=true multibackup
```

Can you give me the full output?

**Comment by swayoleg** [comment]
DEBUG=true multibackup
+ CONFIG=/root/.multibackup.conf
++ tput setaf 1
+ color_red=''
++ tput setaf 3
+ color_yellow=''
++ tput setaf 2
+ color_green=''
++ tput sgr0
+ color_reset=''
+ [[ -f /root/.multibackup.conf ]]
+ . /root/.multibackup.conf
+++ date +%Y%m%d
++ timestamp=20170213
++ backup_destination=/var/www/BACKUPS
++ folders_to_backup=("/var/www/domaine.name")
++ tar_excludes=()
++ backup_retention=+11
++ pre_commands=('mysqldump salon_bd -u salon_bd -ppasswordvalue | bzip2 -c > /var/www/domaine.name/db.sql.bz')
++ post_commands=('rm /var/www/domaine.name/db.sql.bz2')
+ tar_exclude_parameters=()
+ [[ 0 -ne 0 ]]
+ current_action=pre-command
+ current_task=1
+ total_tasks=1
+ [[ 1 -ne 0 ]]
+ info 'Found pre commands...'
++ prefix
++ [[ -n pre-command ]]
++ [[ -n 1 ]]
++ [[ -n 1 ]]
++ echo '[pre-command] [1/1] '
+ echo '[pre-command] [1/1] [INFO] Found pre commands...'
[pre-command] [1/1] [INFO] Found pre commands...
+ for pre_command in '"${pre_commands[@]}"'
+ info 'Running "mysqldump salon_bd -u salon_bd -ppasswordvalue | bzip2 -c > /var/www/domaine.name/db.sql.bz":'
++ prefix
++ [[ -n pre-command ]]
++ [[ -n 1 ]]
++ [[ -n 1 ]]
++ echo '[pre-command] [1/1] '
+ echo '[pre-command] [1/1] [INFO] Running "mysqldump salon_bd -u salon_bd -ppasswordvalue | bzip2 -c > /var/www/domaine.name/db.sql.bz":'
[pre-command] [1/1] [INFO] Running "mysqldump salon_bd -u salon_bd -ppasswordvalue | bzip2 -c > /var/www/domaine.name/db.sql.bz":
+ [[ -n mysqldump salon_bd -u salon_bd -ppasswordvalue | bzip2 -c > /var/www/domaine.name/db.sql.bz ]]
+ success 'Pre command "mysqldump salon_bd -u salon_bd -ppasswordvalue | bzip2 -c > /var/www/domaine.name/db.sql.bz" successfully completed!'
++ prefix
++ [[ -n pre-command ]]
++ [[ -n 1 ]]
++ [[ -n 1 ]]
++ echo '[pre-command] [1/1] '
+ echo '[pre-command] [1/1] [SUCCESS] Pre command "mysqldump salon_bd -u salon_bd -ppasswordvalue | bzip2 -c > /var/www/domaine.name/db.sql.bz" successfully completed!'
[pre-command] [1/1] [SUCCESS] Pre command "mysqldump salon_bd -u salon_bd -ppasswordvalue | bzip2 -c > /var/www/domaine.name/db.sql.bz" successfully completed!
+ bzip2 -c
+ mysqldump salon_bd -u salon_bd -ppasswordvalue
++ date +%Y-%m-%d
+ current_action=backup
+ current_task=1
+ total_tasks=1
+ for folder_to_backup in '"${folders_to_backup[@]}"'
+ debug 'Check if source folder "/var/www/domaine.name" exists...'
++ prefix
++ [[ -n backup ]]
++ [[ -n 1 ]]
++ [[ -n 1 ]]
++ echo '[backup] [1/1] '
+ echo '[backup] [1/1] [DEBUG] Check if source folder "/var/www/domaine.name" exists... '
[backup] [1/1] [DEBUG] Check if source folder "/var/www/domaine.name" exists... 
+ [[ -d /var/www/domaine.name ]]
+ info 'Source folder "/var/www/domaine.name" exists!'
++ prefix
++ [[ -n backup ]]
++ [[ -n 1 ]]
++ [[ -n 1 ]]
++ echo '[backup] [1/1] '
+ echo '[backup] [1/1] [INFO] Source folder "/var/www/domaine.name" exists!'
[backup] [1/1] [INFO] Source folder "/var/www/domaine.name" exists!
++ replace_slash_with_dash /var/www/domaine.name
++ input=-var-www-domaine.name
++ input=var-www-domaine.name
++ output=var-www-domaine.name
++ echo var-www-domaine.name
+ backup_basename=var-www-domaine.name
++ strip_duplicate_slashes_in_path /var/www/BACKUPS/var-www-domaine.name
+++ shopt -p
++ shoptBackup='shopt -u autocd
shopt -u cdable_vars
shopt -u cdspell
shopt -u checkhash
shopt -u checkjobs
shopt -u checkwinsize
shopt -s cmdhist
shopt -u compat31
shopt -u compat32
shopt -u compat40
shopt -u compat41
shopt -u compat42
shopt -s complete_fullquote
shopt -u direxpand
shopt -u dirspell
shopt -u dotglob
shopt -u execfail
shopt -u expand_aliases
shopt -u extdebug
shopt -u extglob
shopt -s extquote
shopt -u failglob
shopt -s force_fignore
shopt -u globstar
shopt -u globasciiranges
shopt -u gnu_errfmt
shopt -u histappend
shopt -u histreedit
shopt -u histverify
shopt -s hostcomplete
shopt -u huponexit
shopt -s interactive_comments
shopt -u lastpipe
shopt -u lithist
shopt -u login_shell
shopt -u mailwarn
shopt -u no_empty_cmd_completion
shopt -u nocaseglob
shopt -u nocasematch
shopt -u nullglob
shopt -s progcomp
shopt -s promptvars
shopt -u restricted_shell
shopt -u shift_verbose
shopt -s sourcepath
shopt -u xpg_echo'
++ shopt -s extglob
++ echo /var/www/BACKUPS/var-www-domaine.name
++ eval ''
+ absolute_backup_destination=/var/www/BACKUPS/var-www-domaine.name
+ [[ ! -d /var/www/BACKUPS/var-www-domaine.name ]]
+ [[ -f /var/www/BACKUPS/var-www-domaine.name/20170213.tar.gz ]]
+ info 'Starting backup "/var/www/BACKUPS/var-www-domain.name/20170213.tar.gz"'
++ prefix
++ [[ -n backup ]]
++ [[ -n 1 ]]
++ [[ -n 1 ]]
++ echo '[backup] [1/1] '
+ echo '[backup] [1/1] [INFO] Starting backup "/var/www/BACKUPS/var-www-domaine.name/20170213.tar.gz"'
[backup] [1/1] [INFO] Starting backup "/var/www/BACKUPS/var-www-domaine.name/20170213.tar.gz"
+ tar czf /var/www/BACKUPS/var-www-domaine.name/20170213.tar.gz -P /var/www/domaine.name

**Comment by swayoleg** [comment]
It still echoes command without executing.
Could you please show me part of the code at your script which will execute pre-command, not show it?

**Comment by swayoleg** [comment]
Due to this
http://stackoverflow.com/questions/2005192/how-to-execute-a-bash-command-stored-as-a-string-with-quotes-and-asterisk
it should be some eval ?

**Comment by frdmn** [comment]
Yup, sounds exactly like the problem you describe, try this instead please:


```bash
# Iterate through post_commnads
if [[ "${#post_commands[@]}" -ne 0 ]]; then
  info "Found post commands..."
  # Run each post command
  for post_command in "${post_commands[@]}"; do
    info "Running \"${post_command}\":"
    eval ${post_command}
    # Check if post command ran successfully
    if [[ $? -eq 0 ]]; then
      success "Post command \"${post_command}\" successfully completed!"
    else
      error "Post command \"${post_command}\" failed..."
    fi
  done
fi
```

Thats probably a more clean way to accomplish this. If you confirm this, I'll push an update

**Comment by bravo-kernel** [comment]
@frdmn your suggested change solves a problem I was having with Percona hot backup before so an update would be appreciated. This now works for me:

```bash
xtrabackup --backup --target-dir=/host/backups/mysql
```

**Comment by bravo-kernel** [comment]
Thank you mr. @frdmn, much obliged ☺️

**Comment by frdmn** [comment]
@bravo-kernel Very welcome :)
